// NB: This file is autogenerated from `generate/math.swift`. Don't change it manually.

import Accelerate

/// SWKStorage extensions for Float.
extension SWKStorage where T == Float {
  /// Cloning sine function.
  public func sin() -> SWKStorage<T> {
    return cloneWith { newStorage in
      vvsinf(newStorage.storage, storage, &size32)
    }
  }

  /// In-place sine function.
  public func sin_() {
    vvsinf(storage, storage, &size32)
  }

  /// Cloning cosine function.
  public func cos() -> SWKStorage<T> {
    return cloneWith { newStorage in
      vvcosf(newStorage.storage, storage, &size32)
    }
  }

  /// In-place cosine function.
  public func cos_() {
    vvcosf(storage, storage, &size32)
  }
}
