// NB: autogenerated from Sources/Generator/main.swift

import Accelerate

/// SWKStorage extension for Double.
extension SWKStorage where T == Double {
  /// Cloning cosine function.
  public func cos() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvcos(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place cosine function.
  public func cos_() {
    vvcos(storage, storage, &size32)
  }

  /// Cloning sine function.
  public func sin() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvsin(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place sine function.
  public func sin_() {
    vvsin(storage, storage, &size32)
  }

  /// Cloning tangent function.
  public func tan() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvtan(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place tangent function.
  public func tan_() {
    vvtan(storage, storage, &size32)
  }

  /// Cloning arccosine function.
  public func acos() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvacos(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place arccosine function.
  public func acos_() {
    vvacos(storage, storage, &size32)
  }

  /// Cloning arcsine function.
  public func asin() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvasin(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place arcsine function.
  public func asin_() {
    vvasin(storage, storage, &size32)
  }

  /// Cloning arctangent function.
  public func atan() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvatan(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place arctangent function.
  public func atan_() {
    vvatan(storage, storage, &size32)
  }

  /// Cloning hyperbolic cosine function.
  public func cosh() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvcosh(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place hyperbolic cosine function.
  public func cosh_() {
    vvcosh(storage, storage, &size32)
  }

  /// Cloning hyperbolic sine function.
  public func sinh() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvsinh(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place hyperbolic sine function.
  public func sinh_() {
    vvsinh(storage, storage, &size32)
  }

  /// Cloning hyperbolic tangent function.
  public func tanh() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvtanh(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place hyperbolic tangent function.
  public func tanh_() {
    vvtanh(storage, storage, &size32)
  }

  /// Cloning inverse hyperbolic cosine function.
  public func acosh() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvacosh(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place inverse hyperbolic cosine function.
  public func acosh_() {
    vvacosh(storage, storage, &size32)
  }

  /// Cloning inverse hyperbolic sine function.
  public func asinh() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvasinh(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place inverse hyperbolic sine function.
  public func asinh_() {
    vvasinh(storage, storage, &size32)
  }

  /// Cloning inverse hyperbolic tangent function.
  public func atanh() -> SWKStorage<T> {
    let newStorage = SWKStorage(size)
    vvatanh(newStorage.storage, storage, &size32)
    return newStorage
  }

  /// In-place inverse hyperbolic tangent function.
  public func atanh_() {
    vvatanh(storage, storage, &size32)
  }

}
