import AST

for type in ["Float", "Double"] {
  createSourceFile(name: "SWKStorage+" + type) { src in
    src.comment("NB: autogenerated file")
    src.empty()
    src.docComment("SWKStorage extension for " + type + ".")
    src.typeExtension("SWKStorage", "T == " + type) { ext in
      // TODO: generate functions
    }
  }
}
